/********************************************************************************
** Form generated from reading UI file 'basic_data_dialog.ui'
**
** Created: Tue Nov 11 16:25:22 2014
**      by: Qt User Interface Compiler version 4.8.2
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_BASIC_DATA_DIALOG_H
#define UI_BASIC_DATA_DIALOG_H

#include <QVariant>
#include <QAction>
#include <QApplication>
#include <QButtonGroup>
#include <QComboBox>
#include <QHeaderView>
#include <QLabel>
#include <QLineEdit>
#include <QPushButton>
#include <QScrollArea>
#include <QStackedWidget>
#include <QTableView>
#include <QVBoxLayout>
#include <QWidget>

QT_BEGIN_NAMESPACE

class Ui_Basic_Data_Dialog
{
public:
    QScrollArea *scrollArea;
    QWidget *scrollAreaWidgetContents;
    QStackedWidget *stackedWidget;
    QWidget *Categoriy_Page;
    QTableView *Category_tableView;
    QLabel *label_3;
    QLineEdit *Category_Name_lineEdit;
    QLabel *label_4;
    QLineEdit *Category_Class_lineEdit;
    QPushButton *Add_Category_pushButton;
    QPushButton *Modify_Category_pushButton;
    QPushButton *Save_Category_pushButton;
    QPushButton *Cancel_Category_pushButton_;
    QPushButton *Delete_Category_pushButton_;
    QWidget *Color_page;
    QTableView *Color_tableView;
    QLabel *label_5;
    QLineEdit *Color_Name_lineEdit;
    QPushButton *Cancel_Color_pushButton;
    QPushButton *Modify_Color_pushButton;
    QPushButton *Delete_Color_pushButton;
    QPushButton *Add_Color_pushButton;
    QPushButton *Save_Color_pushButton;
    QWidget *Unit_page;
    QTableView *Unit_tableView;
    QPushButton *Save_Unit_pushButton;
    QPushButton *Cancle_Unit_pushButton;
    QPushButton *Delete_Unit_pushButton;
    QPushButton *Add_Unit_pushButton;
    QPushButton *Modify_Unit_pushButton;
    QLabel *label_6;
    QLineEdit *Unit_Name_lineEdit;
    QWidget *Auto_page;
    QTableView *Auto_tableView;
    QPushButton *Add_Unit_pushButton_2;
    QPushButton *Modify_Unit_pushButton_2;
    QPushButton *Save_Unit_pushButton_2;
    QPushButton *Cancle_Unit_pushButton_2;
    QPushButton *Delete_Unit_pushButton_2;
    QLabel *label_7;
    QComboBox *Original_comboBox;
    QLabel *label_8;
    QComboBox *Goal_comboBox;
    QLabel *label;
    QLineEdit *lineEdit_6;
    QLineEdit *lineEdit_3;
    QLabel *label_9;
    QLineEdit *lineEdit_2;
    QLabel *label_10;
    QLabel *label_11;
    QLineEdit *lineEdit_5;
    QLabel *label_12;
    QLineEdit *lineEdit_4;
    QLabel *label_13;
    QComboBox *comboBox;
    QWidget *Supplier_Page;
    QTableView *Supplier_tableView;
    QLineEdit *lineEdit_9;
    QLineEdit *lineEdit_7;
    QLineEdit *lineEdit_11;
    QLabel *label_14;
    QLabel *label_16;
    QLabel *label_18;
    QLabel *label_15;
    QLineEdit *lineEdit_8;
    QLabel *label_17;
    QLineEdit *lineEdit_10;
    QLabel *label_19;
    QLineEdit *lineEdit_12;
    QPushButton *Add_Unit_pushButton_3;
    QPushButton *Modify_Unit_pushButton_3;
    QPushButton *Save_Unit_pushButton_3;
    QPushButton *Cancle_Unit_pushButton_3;
    QPushButton *Delete_Unit_pushButton_3;
    QWidget *Vip_Type_page;
    QTableView *tableView;
    QLabel *label_22;
    QPushButton *Add_Vip_pushButton;
    QPushButton *Modify_Vip_pushButton;
    QPushButton *Save_Vip_pushButton;
    QPushButton *Cancle_Vip_pushButton;
    QPushButton *Delete_Vip_pushButton;
    QLabel *label_20;
    QLineEdit *Vip_Name_lineEdit;
    QLabel *label_21;
    QLineEdit *Discounts_lineEdit;
    QWidget *Adjust_page;
    QTableView *Adjust_tableView;
    QLabel *label_23;
    QLineEdit *Adjust_Name_lineEdit;
    QPushButton *Add_Adjust_pushButton;
    QPushButton *Modify_Adjust_pushButton;
    QPushButton *Save_Adjust_pushButton;
    QPushButton *Cancle_Adjust_pushButton;
    QPushButton *Delete_Adjust_pushButton;
    QWidget *Allocation_page;
    QTableView *Allocation_tableView;
    QLabel *label_24;
    QLineEdit *Allocation_lineEdit;
    QPushButton *Add_Allocation_pushButton;
    QPushButton *Modify_Allocation_pushButton;
    QPushButton *Save_Allocation_pushButton;
    QPushButton *Cancle_Allocation_pushButton;
    QPushButton *Delete_Allocation_pushButton;
    QWidget *Brand_page;
    QTableView *Brand_tableView;
    QLabel *label_2;
    QLineEdit *lineEdit;
    QPushButton *Add_Brand_pushButton;
    QPushButton *Modify_Brand_pushButton;
    QPushButton *Save_Brand_pushButton;
    QPushButton *Cancel_Brand_pushButton;
    QPushButton *Delete_Brand_pushButton;
    QScrollArea *scrollArea_2;
    QWidget *scrollAreaWidgetContents_2;
    QWidget *layoutWidget;
    QVBoxLayout *verticalLayout_2;
    QPushButton *Brand_pushButton;
    QPushButton *Categoriy_pushButton;
    QPushButton *Color_pushButton;
    QPushButton *Unit_pushButton;
    QPushButton *Auto_pushButton;
    QPushButton *Supplier_pushButton;
    QPushButton *VIP_pushButton;
    QPushButton *Adjust_pushButton;
    QPushButton *Allocation_pushButton;
    QLabel *Title_label;

    void setupUi(QWidget *Basic_Data_Dialog)
    {
        if (Basic_Data_Dialog->objectName().isEmpty())
            Basic_Data_Dialog->setObjectName(QString::fromUtf8("Basic_Data_Dialog"));
        Basic_Data_Dialog->resize(733, 489);
        Basic_Data_Dialog->setStyleSheet(QString::fromUtf8("background-image: url(:/images/background.jpg);"));
        scrollArea = new QScrollArea(Basic_Data_Dialog);
        scrollArea->setObjectName(QString::fromUtf8("scrollArea"));
        scrollArea->setGeometry(QRect(10, 30, 581, 451));
        scrollArea->setWidgetResizable(true);
        scrollAreaWidgetContents = new QWidget();
        scrollAreaWidgetContents->setObjectName(QString::fromUtf8("scrollAreaWidgetContents"));
        scrollAreaWidgetContents->setGeometry(QRect(0, 0, 579, 449));
        stackedWidget = new QStackedWidget(scrollAreaWidgetContents);
        stackedWidget->setObjectName(QString::fromUtf8("stackedWidget"));
        stackedWidget->setGeometry(QRect(0, 10, 561, 421));
        Categoriy_Page = new QWidget();
        Categoriy_Page->setObjectName(QString::fromUtf8("Categoriy_Page"));
        Category_tableView = new QTableView(Categoriy_Page);
        Category_tableView->setObjectName(QString::fromUtf8("Category_tableView"));
        Category_tableView->setGeometry(QRect(10, 10, 331, 311));
        label_3 = new QLabel(Categoriy_Page);
        label_3->setObjectName(QString::fromUtf8("label_3"));
        label_3->setGeometry(QRect(361, 41, 80, 16));
        QFont font;
        font.setPointSize(11);
        font.setBold(true);
        font.setWeight(75);
        label_3->setFont(font);
        label_3->setStyleSheet(QString::fromUtf8("background:transparent"));
        Category_Name_lineEdit = new QLineEdit(Categoriy_Page);
        Category_Name_lineEdit->setObjectName(QString::fromUtf8("Category_Name_lineEdit"));
        Category_Name_lineEdit->setGeometry(QRect(361, 69, 118, 24));
        Category_Name_lineEdit->setStyleSheet(QString::fromUtf8("border: 2px groove gray; border-radius: 10px; padding: 2px 4px"));
        label_4 = new QLabel(Categoriy_Page);
        label_4->setObjectName(QString::fromUtf8("label_4"));
        label_4->setGeometry(QRect(361, 99, 112, 16));
        label_4->setFont(font);
        label_4->setStyleSheet(QString::fromUtf8("background:transparent"));
        Category_Class_lineEdit = new QLineEdit(Categoriy_Page);
        Category_Class_lineEdit->setObjectName(QString::fromUtf8("Category_Class_lineEdit"));
        Category_Class_lineEdit->setGeometry(QRect(361, 126, 118, 24));
        Category_Class_lineEdit->setStyleSheet(QString::fromUtf8("border: 2px groove gray; border-radius: 10px; padding: 2px 4px"));
        Add_Category_pushButton = new QPushButton(Categoriy_Page);
        Add_Category_pushButton->setObjectName(QString::fromUtf8("Add_Category_pushButton"));
        Add_Category_pushButton->setGeometry(QRect(51, 358, 80, 30));
        Add_Category_pushButton->setStyleSheet(QString::fromUtf8("border: 2px groove gray; border-radius: 10px; padding: 2px 4px"));
        Modify_Category_pushButton = new QPushButton(Categoriy_Page);
        Modify_Category_pushButton->setObjectName(QString::fromUtf8("Modify_Category_pushButton"));
        Modify_Category_pushButton->setGeometry(QRect(132, 358, 80, 30));
        Modify_Category_pushButton->setStyleSheet(QString::fromUtf8("border: 2px groove gray; border-radius: 10px; padding: 2px 4px"));
        Save_Category_pushButton = new QPushButton(Categoriy_Page);
        Save_Category_pushButton->setObjectName(QString::fromUtf8("Save_Category_pushButton"));
        Save_Category_pushButton->setGeometry(QRect(213, 358, 80, 30));
        Save_Category_pushButton->setStyleSheet(QString::fromUtf8("border: 2px groove gray; border-radius: 10px; padding: 2px 4px"));
        Cancel_Category_pushButton_ = new QPushButton(Categoriy_Page);
        Cancel_Category_pushButton_->setObjectName(QString::fromUtf8("Cancel_Category_pushButton_"));
        Cancel_Category_pushButton_->setGeometry(QRect(294, 358, 80, 30));
        Cancel_Category_pushButton_->setStyleSheet(QString::fromUtf8("border: 2px groove gray; border-radius: 10px; padding: 2px 4px"));
        Delete_Category_pushButton_ = new QPushButton(Categoriy_Page);
        Delete_Category_pushButton_->setObjectName(QString::fromUtf8("Delete_Category_pushButton_"));
        Delete_Category_pushButton_->setGeometry(QRect(375, 358, 80, 30));
        Delete_Category_pushButton_->setStyleSheet(QString::fromUtf8("border: 2px groove gray; border-radius: 10px; padding: 2px 4px"));
        stackedWidget->addWidget(Categoriy_Page);
        Color_page = new QWidget();
        Color_page->setObjectName(QString::fromUtf8("Color_page"));
        Color_tableView = new QTableView(Color_page);
        Color_tableView->setObjectName(QString::fromUtf8("Color_tableView"));
        Color_tableView->setGeometry(QRect(10, 10, 511, 311));
        label_5 = new QLabel(Color_page);
        label_5->setObjectName(QString::fromUtf8("label_5"));
        label_5->setGeometry(QRect(160, 336, 60, 16));
        label_5->setStyleSheet(QString::fromUtf8("background:transparent"));
        Color_Name_lineEdit = new QLineEdit(Color_page);
        Color_Name_lineEdit->setObjectName(QString::fromUtf8("Color_Name_lineEdit"));
        Color_Name_lineEdit->setGeometry(QRect(226, 332, 191, 24));
        Color_Name_lineEdit->setStyleSheet(QString::fromUtf8("border: 2px groove gray; border-radius: 10px; padding: 2px 4px"));
        Cancel_Color_pushButton = new QPushButton(Color_page);
        Cancel_Color_pushButton->setObjectName(QString::fromUtf8("Cancel_Color_pushButton"));
        Cancel_Color_pushButton->setGeometry(QRect(338, 369, 80, 30));
        Cancel_Color_pushButton->setStyleSheet(QString::fromUtf8("border: 2px groove gray; border-radius: 10px; padding: 2px 4px"));
        Modify_Color_pushButton = new QPushButton(Color_page);
        Modify_Color_pushButton->setObjectName(QString::fromUtf8("Modify_Color_pushButton"));
        Modify_Color_pushButton->setGeometry(QRect(160, 370, 80, 30));
        Modify_Color_pushButton->setStyleSheet(QString::fromUtf8("border: 2px groove gray; border-radius: 10px; padding: 2px 4px"));
        Delete_Color_pushButton = new QPushButton(Color_page);
        Delete_Color_pushButton->setObjectName(QString::fromUtf8("Delete_Color_pushButton"));
        Delete_Color_pushButton->setGeometry(QRect(431, 369, 80, 30));
        Delete_Color_pushButton->setStyleSheet(QString::fromUtf8("border: 2px groove gray; border-radius: 10px; padding: 2px 4px"));
        Add_Color_pushButton = new QPushButton(Color_page);
        Add_Color_pushButton->setObjectName(QString::fromUtf8("Add_Color_pushButton"));
        Add_Color_pushButton->setGeometry(QRect(71, 372, 80, 30));
        Add_Color_pushButton->setStyleSheet(QString::fromUtf8("border: 2px groove gray; border-radius: 10px; padding: 2px 4px"));
        Save_Color_pushButton = new QPushButton(Color_page);
        Save_Color_pushButton->setObjectName(QString::fromUtf8("Save_Color_pushButton"));
        Save_Color_pushButton->setGeometry(QRect(247, 369, 80, 30));
        Save_Color_pushButton->setStyleSheet(QString::fromUtf8("border: 2px groove gray; border-radius: 10px; padding: 2px 4px"));
        stackedWidget->addWidget(Color_page);
        Unit_page = new QWidget();
        Unit_page->setObjectName(QString::fromUtf8("Unit_page"));
        Unit_tableView = new QTableView(Unit_page);
        Unit_tableView->setObjectName(QString::fromUtf8("Unit_tableView"));
        Unit_tableView->setGeometry(QRect(0, 10, 511, 281));
        Save_Unit_pushButton = new QPushButton(Unit_page);
        Save_Unit_pushButton->setObjectName(QString::fromUtf8("Save_Unit_pushButton"));
        Save_Unit_pushButton->setGeometry(QRect(248, 374, 80, 30));
        Save_Unit_pushButton->setStyleSheet(QString::fromUtf8("border: 2px groove gray; border-radius: 10px; padding: 2px 4px"));
        Cancle_Unit_pushButton = new QPushButton(Unit_page);
        Cancle_Unit_pushButton->setObjectName(QString::fromUtf8("Cancle_Unit_pushButton"));
        Cancle_Unit_pushButton->setGeometry(QRect(347, 373, 80, 30));
        Cancle_Unit_pushButton->setStyleSheet(QString::fromUtf8("border: 2px groove gray; border-radius: 10px; padding: 2px 4px"));
        Delete_Unit_pushButton = new QPushButton(Unit_page);
        Delete_Unit_pushButton->setObjectName(QString::fromUtf8("Delete_Unit_pushButton"));
        Delete_Unit_pushButton->setGeometry(QRect(443, 371, 80, 30));
        Delete_Unit_pushButton->setStyleSheet(QString::fromUtf8("border: 2px groove gray; border-radius: 10px; padding: 2px 4px"));
        Add_Unit_pushButton = new QPushButton(Unit_page);
        Add_Unit_pushButton->setObjectName(QString::fromUtf8("Add_Unit_pushButton"));
        Add_Unit_pushButton->setGeometry(QRect(60, 376, 80, 30));
        Add_Unit_pushButton->setStyleSheet(QString::fromUtf8("border: 2px groove gray; border-radius: 10px; padding: 2px 4px"));
        Modify_Unit_pushButton = new QPushButton(Unit_page);
        Modify_Unit_pushButton->setObjectName(QString::fromUtf8("Modify_Unit_pushButton"));
        Modify_Unit_pushButton->setGeometry(QRect(152, 375, 80, 30));
        Modify_Unit_pushButton->setStyleSheet(QString::fromUtf8("border: 2px groove gray; border-radius: 10px; padding: 2px 4px"));
        label_6 = new QLabel(Unit_page);
        label_6->setObjectName(QString::fromUtf8("label_6"));
        label_6->setGeometry(QRect(127, 324, 60, 16));
        label_6->setStyleSheet(QString::fromUtf8("background:transparent"));
        Unit_Name_lineEdit = new QLineEdit(Unit_page);
        Unit_Name_lineEdit->setObjectName(QString::fromUtf8("Unit_Name_lineEdit"));
        Unit_Name_lineEdit->setGeometry(QRect(194, 321, 211, 24));
        Unit_Name_lineEdit->setStyleSheet(QString::fromUtf8("border: 2px groove gray; border-radius: 10px; padding: 2px 4px"));
        stackedWidget->addWidget(Unit_page);
        Auto_page = new QWidget();
        Auto_page->setObjectName(QString::fromUtf8("Auto_page"));
        Auto_tableView = new QTableView(Auto_page);
        Auto_tableView->setObjectName(QString::fromUtf8("Auto_tableView"));
        Auto_tableView->setGeometry(QRect(10, 1, 541, 201));
        Add_Unit_pushButton_2 = new QPushButton(Auto_page);
        Add_Unit_pushButton_2->setObjectName(QString::fromUtf8("Add_Unit_pushButton_2"));
        Add_Unit_pushButton_2->setGeometry(QRect(63, 371, 80, 30));
        Add_Unit_pushButton_2->setStyleSheet(QString::fromUtf8("border: 2px groove gray; border-radius: 10px; padding: 2px 4px"));
        Modify_Unit_pushButton_2 = new QPushButton(Auto_page);
        Modify_Unit_pushButton_2->setObjectName(QString::fromUtf8("Modify_Unit_pushButton_2"));
        Modify_Unit_pushButton_2->setGeometry(QRect(144, 371, 80, 30));
        Modify_Unit_pushButton_2->setStyleSheet(QString::fromUtf8("border: 2px groove gray; border-radius: 10px; padding: 2px 4px"));
        Save_Unit_pushButton_2 = new QPushButton(Auto_page);
        Save_Unit_pushButton_2->setObjectName(QString::fromUtf8("Save_Unit_pushButton_2"));
        Save_Unit_pushButton_2->setGeometry(QRect(225, 371, 80, 30));
        Save_Unit_pushButton_2->setStyleSheet(QString::fromUtf8("border: 2px groove gray; border-radius: 10px; padding: 2px 4px"));
        Cancle_Unit_pushButton_2 = new QPushButton(Auto_page);
        Cancle_Unit_pushButton_2->setObjectName(QString::fromUtf8("Cancle_Unit_pushButton_2"));
        Cancle_Unit_pushButton_2->setGeometry(QRect(306, 371, 80, 30));
        Cancle_Unit_pushButton_2->setStyleSheet(QString::fromUtf8("border: 2px groove gray; border-radius: 10px; padding: 2px 4px"));
        Delete_Unit_pushButton_2 = new QPushButton(Auto_page);
        Delete_Unit_pushButton_2->setObjectName(QString::fromUtf8("Delete_Unit_pushButton_2"));
        Delete_Unit_pushButton_2->setGeometry(QRect(387, 371, 80, 30));
        Delete_Unit_pushButton_2->setStyleSheet(QString::fromUtf8("border: 2px groove gray; border-radius: 10px; padding: 2px 4px"));
        label_7 = new QLabel(Auto_page);
        label_7->setObjectName(QString::fromUtf8("label_7"));
        label_7->setGeometry(QRect(21, 213, 72, 16));
        QSizePolicy sizePolicy(QSizePolicy::Maximum, QSizePolicy::Preferred);
        sizePolicy.setHorizontalStretch(0);
        sizePolicy.setVerticalStretch(0);
        sizePolicy.setHeightForWidth(label_7->sizePolicy().hasHeightForWidth());
        label_7->setSizePolicy(sizePolicy);
        label_7->setStyleSheet(QString::fromUtf8("background:transparent"));
        Original_comboBox = new QComboBox(Auto_page);
        Original_comboBox->setObjectName(QString::fromUtf8("Original_comboBox"));
        Original_comboBox->setGeometry(QRect(99, 214, 80, 18));
        label_8 = new QLabel(Auto_page);
        label_8->setObjectName(QString::fromUtf8("label_8"));
        label_8->setGeometry(QRect(291, 213, 84, 16));
        sizePolicy.setHeightForWidth(label_8->sizePolicy().hasHeightForWidth());
        label_8->setSizePolicy(sizePolicy);
        label_8->setStyleSheet(QString::fromUtf8("background:transparent"));
        Goal_comboBox = new QComboBox(Auto_page);
        Goal_comboBox->setObjectName(QString::fromUtf8("Goal_comboBox"));
        Goal_comboBox->setGeometry(QRect(381, 214, 80, 18));
        label = new QLabel(Auto_page);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(21, 242, 318, 16));
        label->setStyleSheet(QString::fromUtf8("background:transparent"));
        lineEdit_6 = new QLineEdit(Auto_page);
        lineEdit_6->setObjectName(QString::fromUtf8("lineEdit_6"));
        lineEdit_6->setGeometry(QRect(348, 242, 140, 25));
        lineEdit_6->setStyleSheet(QString::fromUtf8("border: 2px groove gray; border-radius: 10px; padding: 2px 4px"));
        lineEdit_3 = new QLineEdit(Auto_page);
        lineEdit_3->setObjectName(QString::fromUtf8("lineEdit_3"));
        lineEdit_3->setGeometry(QRect(348, 270, 140, 25));
        lineEdit_3->setStyleSheet(QString::fromUtf8("border: 2px groove gray; border-radius: 10px; padding: 2px 4px"));
        label_9 = new QLabel(Auto_page);
        label_9->setObjectName(QString::fromUtf8("label_9"));
        label_9->setGeometry(QRect(21, 270, 72, 16));
        label_9->setStyleSheet(QString::fromUtf8("background:transparent"));
        lineEdit_2 = new QLineEdit(Auto_page);
        lineEdit_2->setObjectName(QString::fromUtf8("lineEdit_2"));
        lineEdit_2->setGeometry(QRect(99, 270, 140, 25));
        lineEdit_2->setStyleSheet(QString::fromUtf8("border: 2px groove gray; border-radius: 10px; padding: 2px 4px"));
        label_10 = new QLabel(Auto_page);
        label_10->setObjectName(QString::fromUtf8("label_10"));
        label_10->setGeometry(QRect(258, 270, 84, 16));
        label_10->setStyleSheet(QString::fromUtf8("background:transparent"));
        label_11 = new QLabel(Auto_page);
        label_11->setObjectName(QString::fromUtf8("label_11"));
        label_11->setGeometry(QRect(21, 300, 72, 16));
        label_11->setStyleSheet(QString::fromUtf8("background:transparent"));
        lineEdit_5 = new QLineEdit(Auto_page);
        lineEdit_5->setObjectName(QString::fromUtf8("lineEdit_5"));
        lineEdit_5->setGeometry(QRect(99, 300, 140, 25));
        lineEdit_5->setStyleSheet(QString::fromUtf8("border: 2px groove gray; border-radius: 10px; padding: 2px 4px"));
        label_12 = new QLabel(Auto_page);
        label_12->setObjectName(QString::fromUtf8("label_12"));
        label_12->setGeometry(QRect(258, 300, 84, 16));
        label_12->setStyleSheet(QString::fromUtf8("background:transparent"));
        lineEdit_4 = new QLineEdit(Auto_page);
        lineEdit_4->setObjectName(QString::fromUtf8("lineEdit_4"));
        lineEdit_4->setGeometry(QRect(348, 300, 140, 25));
        lineEdit_4->setStyleSheet(QString::fromUtf8("border: 2px groove gray; border-radius: 10px; padding: 2px 4px"));
        label_13 = new QLabel(Auto_page);
        label_13->setObjectName(QString::fromUtf8("label_13"));
        label_13->setGeometry(QRect(21, 328, 168, 16));
        sizePolicy.setHeightForWidth(label_13->sizePolicy().hasHeightForWidth());
        label_13->setSizePolicy(sizePolicy);
        label_13->setStyleSheet(QString::fromUtf8("background:transparent"));
        comboBox = new QComboBox(Auto_page);
        comboBox->setObjectName(QString::fromUtf8("comboBox"));
        comboBox->setGeometry(QRect(195, 328, 186, 18));
        comboBox->setStyleSheet(QString::fromUtf8(""));
        stackedWidget->addWidget(Auto_page);
        Supplier_Page = new QWidget();
        Supplier_Page->setObjectName(QString::fromUtf8("Supplier_Page"));
        Supplier_tableView = new QTableView(Supplier_Page);
        Supplier_tableView->setObjectName(QString::fromUtf8("Supplier_tableView"));
        Supplier_tableView->setGeometry(QRect(10, 10, 551, 231));
        lineEdit_9 = new QLineEdit(Supplier_Page);
        lineEdit_9->setObjectName(QString::fromUtf8("lineEdit_9"));
        lineEdit_9->setGeometry(QRect(130, 279, 118, 24));
        lineEdit_9->setStyleSheet(QString::fromUtf8("border: 2px groove gray; border-radius: 10px; padding: 2px 4px"));
        lineEdit_7 = new QLineEdit(Supplier_Page);
        lineEdit_7->setObjectName(QString::fromUtf8("lineEdit_7"));
        lineEdit_7->setGeometry(QRect(130, 250, 118, 24));
        lineEdit_7->setStyleSheet(QString::fromUtf8("border: 2px groove gray; border-radius: 10px; padding: 2px 4px"));
        lineEdit_11 = new QLineEdit(Supplier_Page);
        lineEdit_11->setObjectName(QString::fromUtf8("lineEdit_11"));
        lineEdit_11->setGeometry(QRect(130, 311, 118, 24));
        lineEdit_11->setStyleSheet(QString::fromUtf8("border: 2px groove gray; border-radius: 10px; padding: 2px 4px"));
        label_14 = new QLabel(Supplier_Page);
        label_14->setObjectName(QString::fromUtf8("label_14"));
        label_14->setGeometry(QRect(61, 250, 36, 16));
        label_14->setStyleSheet(QString::fromUtf8("background:transparent"));
        label_16 = new QLabel(Supplier_Page);
        label_16->setObjectName(QString::fromUtf8("label_16"));
        label_16->setGeometry(QRect(61, 279, 36, 16));
        label_16->setStyleSheet(QString::fromUtf8("background:transparent"));
        label_18 = new QLabel(Supplier_Page);
        label_18->setObjectName(QString::fromUtf8("label_18"));
        label_18->setGeometry(QRect(61, 311, 60, 16));
        label_18->setStyleSheet(QString::fromUtf8("background:transparent"));
        label_15 = new QLabel(Supplier_Page);
        label_15->setObjectName(QString::fromUtf8("label_15"));
        label_15->setGeometry(QRect(341, 253, 48, 16));
        label_15->setStyleSheet(QString::fromUtf8("background:transparent"));
        lineEdit_8 = new QLineEdit(Supplier_Page);
        lineEdit_8->setObjectName(QString::fromUtf8("lineEdit_8"));
        lineEdit_8->setGeometry(QRect(395, 253, 118, 24));
        lineEdit_8->setStyleSheet(QString::fromUtf8("border: 2px groove gray; border-radius: 10px; padding: 2px 4px"));
        label_17 = new QLabel(Supplier_Page);
        label_17->setObjectName(QString::fromUtf8("label_17"));
        label_17->setGeometry(QRect(341, 283, 36, 16));
        label_17->setStyleSheet(QString::fromUtf8("background:transparent"));
        lineEdit_10 = new QLineEdit(Supplier_Page);
        lineEdit_10->setObjectName(QString::fromUtf8("lineEdit_10"));
        lineEdit_10->setGeometry(QRect(395, 283, 118, 24));
        lineEdit_10->setStyleSheet(QString::fromUtf8("border: 2px groove gray; border-radius: 10px; padding: 2px 4px"));
        label_19 = new QLabel(Supplier_Page);
        label_19->setObjectName(QString::fromUtf8("label_19"));
        label_19->setGeometry(QRect(61, 344, 36, 16));
        label_19->setStyleSheet(QString::fromUtf8("background:transparent"));
        lineEdit_12 = new QLineEdit(Supplier_Page);
        lineEdit_12->setObjectName(QString::fromUtf8("lineEdit_12"));
        lineEdit_12->setGeometry(QRect(130, 341, 371, 24));
        lineEdit_12->setStyleSheet(QString::fromUtf8("border: 2px groove gray; border-radius: 10px; padding: 2px 4px"));
        Add_Unit_pushButton_3 = new QPushButton(Supplier_Page);
        Add_Unit_pushButton_3->setObjectName(QString::fromUtf8("Add_Unit_pushButton_3"));
        Add_Unit_pushButton_3->setGeometry(QRect(94, 376, 80, 30));
        Add_Unit_pushButton_3->setStyleSheet(QString::fromUtf8("border: 2px groove gray; border-radius: 10px; padding: 2px 4px"));
        Modify_Unit_pushButton_3 = new QPushButton(Supplier_Page);
        Modify_Unit_pushButton_3->setObjectName(QString::fromUtf8("Modify_Unit_pushButton_3"));
        Modify_Unit_pushButton_3->setGeometry(QRect(175, 376, 80, 30));
        Modify_Unit_pushButton_3->setStyleSheet(QString::fromUtf8("border: 2px groove gray; border-radius: 10px; padding: 2px 4px"));
        Save_Unit_pushButton_3 = new QPushButton(Supplier_Page);
        Save_Unit_pushButton_3->setObjectName(QString::fromUtf8("Save_Unit_pushButton_3"));
        Save_Unit_pushButton_3->setGeometry(QRect(256, 376, 80, 30));
        Save_Unit_pushButton_3->setStyleSheet(QString::fromUtf8("border: 2px groove gray; border-radius: 10px; padding: 2px 4px"));
        Cancle_Unit_pushButton_3 = new QPushButton(Supplier_Page);
        Cancle_Unit_pushButton_3->setObjectName(QString::fromUtf8("Cancle_Unit_pushButton_3"));
        Cancle_Unit_pushButton_3->setGeometry(QRect(337, 376, 80, 30));
        Cancle_Unit_pushButton_3->setStyleSheet(QString::fromUtf8("border: 2px groove gray; border-radius: 10px; padding: 2px 4px"));
        Delete_Unit_pushButton_3 = new QPushButton(Supplier_Page);
        Delete_Unit_pushButton_3->setObjectName(QString::fromUtf8("Delete_Unit_pushButton_3"));
        Delete_Unit_pushButton_3->setGeometry(QRect(418, 376, 80, 30));
        Delete_Unit_pushButton_3->setStyleSheet(QString::fromUtf8("border: 2px groove gray; border-radius: 10px; padding: 2px 4px"));
        stackedWidget->addWidget(Supplier_Page);
        Vip_Type_page = new QWidget();
        Vip_Type_page->setObjectName(QString::fromUtf8("Vip_Type_page"));
        tableView = new QTableView(Vip_Type_page);
        tableView->setObjectName(QString::fromUtf8("tableView"));
        tableView->setGeometry(QRect(10, 0, 551, 281));
        label_22 = new QLabel(Vip_Type_page);
        label_22->setObjectName(QString::fromUtf8("label_22"));
        label_22->setGeometry(QRect(287, 336, 151, 16));
        label_22->setStyleSheet(QString::fromUtf8("background:transparent"));
        Add_Vip_pushButton = new QPushButton(Vip_Type_page);
        Add_Vip_pushButton->setObjectName(QString::fromUtf8("Add_Vip_pushButton"));
        Add_Vip_pushButton->setGeometry(QRect(71, 375, 80, 30));
        Add_Vip_pushButton->setStyleSheet(QString::fromUtf8("border: 2px groove gray; border-radius: 10px; padding: 2px 4px"));
        Modify_Vip_pushButton = new QPushButton(Vip_Type_page);
        Modify_Vip_pushButton->setObjectName(QString::fromUtf8("Modify_Vip_pushButton"));
        Modify_Vip_pushButton->setGeometry(QRect(152, 375, 80, 30));
        Modify_Vip_pushButton->setStyleSheet(QString::fromUtf8("border: 2px groove gray; border-radius: 10px; padding: 2px 4px"));
        Save_Vip_pushButton = new QPushButton(Vip_Type_page);
        Save_Vip_pushButton->setObjectName(QString::fromUtf8("Save_Vip_pushButton"));
        Save_Vip_pushButton->setGeometry(QRect(233, 375, 80, 30));
        Save_Vip_pushButton->setStyleSheet(QString::fromUtf8("border: 2px groove gray; border-radius: 10px; padding: 2px 4px"));
        Cancle_Vip_pushButton = new QPushButton(Vip_Type_page);
        Cancle_Vip_pushButton->setObjectName(QString::fromUtf8("Cancle_Vip_pushButton"));
        Cancle_Vip_pushButton->setGeometry(QRect(314, 375, 80, 30));
        Cancle_Vip_pushButton->setStyleSheet(QString::fromUtf8("border: 2px groove gray; border-radius: 10px; padding: 2px 4px"));
        Delete_Vip_pushButton = new QPushButton(Vip_Type_page);
        Delete_Vip_pushButton->setObjectName(QString::fromUtf8("Delete_Vip_pushButton"));
        Delete_Vip_pushButton->setGeometry(QRect(395, 375, 80, 30));
        Delete_Vip_pushButton->setStyleSheet(QString::fromUtf8("border: 2px groove gray; border-radius: 10px; padding: 2px 4px"));
        label_20 = new QLabel(Vip_Type_page);
        label_20->setObjectName(QString::fromUtf8("label_20"));
        label_20->setGeometry(QRect(91, 298, 60, 16));
        label_20->setStyleSheet(QString::fromUtf8("background:transparent"));
        Vip_Name_lineEdit = new QLineEdit(Vip_Type_page);
        Vip_Name_lineEdit->setObjectName(QString::fromUtf8("Vip_Name_lineEdit"));
        Vip_Name_lineEdit->setGeometry(QRect(157, 295, 118, 24));
        Vip_Name_lineEdit->setStyleSheet(QString::fromUtf8("border: 2px groove gray; border-radius: 10px; padding: 2px 4px"));
        label_21 = new QLabel(Vip_Type_page);
        label_21->setObjectName(QString::fromUtf8("label_21"));
        label_21->setGeometry(QRect(91, 332, 60, 16));
        label_21->setStyleSheet(QString::fromUtf8("background:transparent"));
        Discounts_lineEdit = new QLineEdit(Vip_Type_page);
        Discounts_lineEdit->setObjectName(QString::fromUtf8("Discounts_lineEdit"));
        Discounts_lineEdit->setGeometry(QRect(157, 332, 118, 24));
        Discounts_lineEdit->setStyleSheet(QString::fromUtf8("border: 2px groove gray; border-radius: 10px; padding: 2px 4px"));
        stackedWidget->addWidget(Vip_Type_page);
        Adjust_page = new QWidget();
        Adjust_page->setObjectName(QString::fromUtf8("Adjust_page"));
        Adjust_tableView = new QTableView(Adjust_page);
        Adjust_tableView->setObjectName(QString::fromUtf8("Adjust_tableView"));
        Adjust_tableView->setGeometry(QRect(10, 10, 551, 291));
        label_23 = new QLabel(Adjust_page);
        label_23->setObjectName(QString::fromUtf8("label_23"));
        label_23->setGeometry(QRect(199, 328, 60, 16));
        label_23->setStyleSheet(QString::fromUtf8("background:transparent"));
        Adjust_Name_lineEdit = new QLineEdit(Adjust_page);
        Adjust_Name_lineEdit->setObjectName(QString::fromUtf8("Adjust_Name_lineEdit"));
        Adjust_Name_lineEdit->setGeometry(QRect(265, 324, 118, 24));
        Adjust_Name_lineEdit->setStyleSheet(QString::fromUtf8("border: 2px groove gray; border-radius: 10px; padding: 2px 4px"));
        Add_Adjust_pushButton = new QPushButton(Adjust_page);
        Add_Adjust_pushButton->setObjectName(QString::fromUtf8("Add_Adjust_pushButton"));
        Add_Adjust_pushButton->setGeometry(QRect(81, 362, 80, 30));
        Add_Adjust_pushButton->setStyleSheet(QString::fromUtf8("border: 2px groove gray; border-radius: 10px; padding: 2px 4px"));
        Modify_Adjust_pushButton = new QPushButton(Adjust_page);
        Modify_Adjust_pushButton->setObjectName(QString::fromUtf8("Modify_Adjust_pushButton"));
        Modify_Adjust_pushButton->setGeometry(QRect(162, 362, 80, 30));
        Modify_Adjust_pushButton->setStyleSheet(QString::fromUtf8("border: 2px groove gray; border-radius: 10px; padding: 2px 4px"));
        Save_Adjust_pushButton = new QPushButton(Adjust_page);
        Save_Adjust_pushButton->setObjectName(QString::fromUtf8("Save_Adjust_pushButton"));
        Save_Adjust_pushButton->setGeometry(QRect(243, 362, 80, 30));
        Save_Adjust_pushButton->setStyleSheet(QString::fromUtf8("border: 2px groove gray; border-radius: 10px; padding: 2px 4px"));
        Cancle_Adjust_pushButton = new QPushButton(Adjust_page);
        Cancle_Adjust_pushButton->setObjectName(QString::fromUtf8("Cancle_Adjust_pushButton"));
        Cancle_Adjust_pushButton->setGeometry(QRect(324, 362, 80, 30));
        Cancle_Adjust_pushButton->setStyleSheet(QString::fromUtf8("border: 2px groove gray; border-radius: 10px; padding: 2px 4px"));
        Delete_Adjust_pushButton = new QPushButton(Adjust_page);
        Delete_Adjust_pushButton->setObjectName(QString::fromUtf8("Delete_Adjust_pushButton"));
        Delete_Adjust_pushButton->setGeometry(QRect(405, 362, 80, 30));
        Delete_Adjust_pushButton->setStyleSheet(QString::fromUtf8("border: 2px groove gray; border-radius: 10px; padding: 2px 4px"));
        stackedWidget->addWidget(Adjust_page);
        Allocation_page = new QWidget();
        Allocation_page->setObjectName(QString::fromUtf8("Allocation_page"));
        Allocation_tableView = new QTableView(Allocation_page);
        Allocation_tableView->setObjectName(QString::fromUtf8("Allocation_tableView"));
        Allocation_tableView->setGeometry(QRect(4, 10, 561, 281));
        label_24 = new QLabel(Allocation_page);
        label_24->setObjectName(QString::fromUtf8("label_24"));
        label_24->setGeometry(QRect(131, 323, 120, 16));
        label_24->setStyleSheet(QString::fromUtf8("background:transparent"));
        Allocation_lineEdit = new QLineEdit(Allocation_page);
        Allocation_lineEdit->setObjectName(QString::fromUtf8("Allocation_lineEdit"));
        Allocation_lineEdit->setGeometry(QRect(257, 321, 118, 24));
        Allocation_lineEdit->setStyleSheet(QString::fromUtf8("border: 2px groove gray; border-radius: 10px; padding: 2px 4px"));
        Add_Allocation_pushButton = new QPushButton(Allocation_page);
        Add_Allocation_pushButton->setObjectName(QString::fromUtf8("Add_Allocation_pushButton"));
        Add_Allocation_pushButton->setGeometry(QRect(81, 362, 80, 30));
        Add_Allocation_pushButton->setStyleSheet(QString::fromUtf8("border: 2px groove gray; border-radius: 10px; padding: 2px 4px"));
        Modify_Allocation_pushButton = new QPushButton(Allocation_page);
        Modify_Allocation_pushButton->setObjectName(QString::fromUtf8("Modify_Allocation_pushButton"));
        Modify_Allocation_pushButton->setGeometry(QRect(162, 362, 80, 30));
        Modify_Allocation_pushButton->setStyleSheet(QString::fromUtf8("border: 2px groove gray; border-radius: 10px; padding: 2px 4px"));
        Save_Allocation_pushButton = new QPushButton(Allocation_page);
        Save_Allocation_pushButton->setObjectName(QString::fromUtf8("Save_Allocation_pushButton"));
        Save_Allocation_pushButton->setGeometry(QRect(243, 362, 80, 30));
        Save_Allocation_pushButton->setStyleSheet(QString::fromUtf8("border: 2px groove gray; border-radius: 10px; padding: 2px 4px"));
        Cancle_Allocation_pushButton = new QPushButton(Allocation_page);
        Cancle_Allocation_pushButton->setObjectName(QString::fromUtf8("Cancle_Allocation_pushButton"));
        Cancle_Allocation_pushButton->setGeometry(QRect(324, 362, 80, 30));
        Cancle_Allocation_pushButton->setStyleSheet(QString::fromUtf8("border: 2px groove gray; border-radius: 10px; padding: 2px 4px"));
        Delete_Allocation_pushButton = new QPushButton(Allocation_page);
        Delete_Allocation_pushButton->setObjectName(QString::fromUtf8("Delete_Allocation_pushButton"));
        Delete_Allocation_pushButton->setGeometry(QRect(405, 362, 80, 30));
        Delete_Allocation_pushButton->setStyleSheet(QString::fromUtf8("border: 2px groove gray; border-radius: 10px; padding: 2px 4px"));
        stackedWidget->addWidget(Allocation_page);
        Brand_page = new QWidget();
        Brand_page->setObjectName(QString::fromUtf8("Brand_page"));
        Brand_tableView = new QTableView(Brand_page);
        Brand_tableView->setObjectName(QString::fromUtf8("Brand_tableView"));
        Brand_tableView->setGeometry(QRect(10, 20, 481, 261));
        label_2 = new QLabel(Brand_page);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(130, 312, 60, 16));
        label_2->setStyleSheet(QString::fromUtf8("background:transparent"));
        lineEdit = new QLineEdit(Brand_page);
        lineEdit->setObjectName(QString::fromUtf8("lineEdit"));
        lineEdit->setGeometry(QRect(196, 309, 118, 24));
        lineEdit->setStyleSheet(QString::fromUtf8("border: 2px groove gray; border-radius: 10px; padding: 2px 4px"));
        Add_Brand_pushButton = new QPushButton(Brand_page);
        Add_Brand_pushButton->setObjectName(QString::fromUtf8("Add_Brand_pushButton"));
        Add_Brand_pushButton->setGeometry(QRect(41, 354, 80, 30));
        Add_Brand_pushButton->setStyleSheet(QString::fromUtf8("border: 2px groove gray; border-radius: 10px; padding: 2px 4px"));
        Modify_Brand_pushButton = new QPushButton(Brand_page);
        Modify_Brand_pushButton->setObjectName(QString::fromUtf8("Modify_Brand_pushButton"));
        Modify_Brand_pushButton->setGeometry(QRect(122, 354, 80, 30));
        Modify_Brand_pushButton->setStyleSheet(QString::fromUtf8("border: 2px groove gray; border-radius: 10px; padding: 2px 4px"));
        Save_Brand_pushButton = new QPushButton(Brand_page);
        Save_Brand_pushButton->setObjectName(QString::fromUtf8("Save_Brand_pushButton"));
        Save_Brand_pushButton->setGeometry(QRect(203, 354, 80, 30));
        Save_Brand_pushButton->setStyleSheet(QString::fromUtf8("border: 2px groove gray; border-radius: 10px; padding: 2px 4px"));
        Cancel_Brand_pushButton = new QPushButton(Brand_page);
        Cancel_Brand_pushButton->setObjectName(QString::fromUtf8("Cancel_Brand_pushButton"));
        Cancel_Brand_pushButton->setGeometry(QRect(284, 354, 80, 30));
        Cancel_Brand_pushButton->setStyleSheet(QString::fromUtf8("border: 2px groove gray; border-radius: 10px; padding: 2px 4px"));
        Delete_Brand_pushButton = new QPushButton(Brand_page);
        Delete_Brand_pushButton->setObjectName(QString::fromUtf8("Delete_Brand_pushButton"));
        Delete_Brand_pushButton->setGeometry(QRect(365, 354, 80, 30));
        Delete_Brand_pushButton->setStyleSheet(QString::fromUtf8("border: 2px groove gray; border-radius: 10px; padding: 2px 4px"));
        stackedWidget->addWidget(Brand_page);
        scrollArea->setWidget(scrollAreaWidgetContents);
        scrollArea_2 = new QScrollArea(Basic_Data_Dialog);
        scrollArea_2->setObjectName(QString::fromUtf8("scrollArea_2"));
        scrollArea_2->setGeometry(QRect(599, 30, 121, 451));
        scrollArea_2->setWidgetResizable(true);
        scrollAreaWidgetContents_2 = new QWidget();
        scrollAreaWidgetContents_2->setObjectName(QString::fromUtf8("scrollAreaWidgetContents_2"));
        scrollAreaWidgetContents_2->setGeometry(QRect(0, 0, 119, 449));
        layoutWidget = new QWidget(scrollAreaWidgetContents_2);
        layoutWidget->setObjectName(QString::fromUtf8("layoutWidget"));
        layoutWidget->setGeometry(QRect(6, 8, 101, 401));
        verticalLayout_2 = new QVBoxLayout(layoutWidget);
        verticalLayout_2->setObjectName(QString::fromUtf8("verticalLayout_2"));
        verticalLayout_2->setContentsMargins(0, 0, 0, 0);
        Brand_pushButton = new QPushButton(layoutWidget);
        Brand_pushButton->setObjectName(QString::fromUtf8("Brand_pushButton"));
        QSizePolicy sizePolicy1(QSizePolicy::Minimum, QSizePolicy::Expanding);
        sizePolicy1.setHorizontalStretch(0);
        sizePolicy1.setVerticalStretch(0);
        sizePolicy1.setHeightForWidth(Brand_pushButton->sizePolicy().hasHeightForWidth());
        Brand_pushButton->setSizePolicy(sizePolicy1);
        Brand_pushButton->setStyleSheet(QString::fromUtf8("border: 2px groove gray; border-radius: 10px; padding: 2px 4px"));

        verticalLayout_2->addWidget(Brand_pushButton);

        Categoriy_pushButton = new QPushButton(layoutWidget);
        Categoriy_pushButton->setObjectName(QString::fromUtf8("Categoriy_pushButton"));
        sizePolicy1.setHeightForWidth(Categoriy_pushButton->sizePolicy().hasHeightForWidth());
        Categoriy_pushButton->setSizePolicy(sizePolicy1);
        Categoriy_pushButton->setStyleSheet(QString::fromUtf8("border: 2px groove gray; border-radius: 10px; padding: 2px 4px"));

        verticalLayout_2->addWidget(Categoriy_pushButton);

        Color_pushButton = new QPushButton(layoutWidget);
        Color_pushButton->setObjectName(QString::fromUtf8("Color_pushButton"));
        sizePolicy1.setHeightForWidth(Color_pushButton->sizePolicy().hasHeightForWidth());
        Color_pushButton->setSizePolicy(sizePolicy1);
        Color_pushButton->setStyleSheet(QString::fromUtf8("border: 2px groove gray; border-radius: 10px; padding: 2px"));

        verticalLayout_2->addWidget(Color_pushButton);

        Unit_pushButton = new QPushButton(layoutWidget);
        Unit_pushButton->setObjectName(QString::fromUtf8("Unit_pushButton"));
        sizePolicy1.setHeightForWidth(Unit_pushButton->sizePolicy().hasHeightForWidth());
        Unit_pushButton->setSizePolicy(sizePolicy1);
        Unit_pushButton->setStyleSheet(QString::fromUtf8("border: 2px groove gray; border-radius: 10px; padding: 2px 4px"));

        verticalLayout_2->addWidget(Unit_pushButton);

        Auto_pushButton = new QPushButton(layoutWidget);
        Auto_pushButton->setObjectName(QString::fromUtf8("Auto_pushButton"));
        sizePolicy1.setHeightForWidth(Auto_pushButton->sizePolicy().hasHeightForWidth());
        Auto_pushButton->setSizePolicy(sizePolicy1);
        Auto_pushButton->setStyleSheet(QString::fromUtf8("border: 2px groove gray; border-radius: 10px; padding: 2px 4px"));

        verticalLayout_2->addWidget(Auto_pushButton);

        Supplier_pushButton = new QPushButton(layoutWidget);
        Supplier_pushButton->setObjectName(QString::fromUtf8("Supplier_pushButton"));
        sizePolicy1.setHeightForWidth(Supplier_pushButton->sizePolicy().hasHeightForWidth());
        Supplier_pushButton->setSizePolicy(sizePolicy1);
        Supplier_pushButton->setStyleSheet(QString::fromUtf8("border: 2px groove gray; border-radius: 10px; padding: 2px 4px"));

        verticalLayout_2->addWidget(Supplier_pushButton);

        VIP_pushButton = new QPushButton(layoutWidget);
        VIP_pushButton->setObjectName(QString::fromUtf8("VIP_pushButton"));
        sizePolicy1.setHeightForWidth(VIP_pushButton->sizePolicy().hasHeightForWidth());
        VIP_pushButton->setSizePolicy(sizePolicy1);
        VIP_pushButton->setStyleSheet(QString::fromUtf8("border: 2px groove gray; border-radius: 10px; padding: 2px 4px"));

        verticalLayout_2->addWidget(VIP_pushButton);

        Adjust_pushButton = new QPushButton(layoutWidget);
        Adjust_pushButton->setObjectName(QString::fromUtf8("Adjust_pushButton"));
        sizePolicy1.setHeightForWidth(Adjust_pushButton->sizePolicy().hasHeightForWidth());
        Adjust_pushButton->setSizePolicy(sizePolicy1);
        Adjust_pushButton->setStyleSheet(QString::fromUtf8("border: 2px groove gray; border-radius: 10px; padding: 2px 4px"));

        verticalLayout_2->addWidget(Adjust_pushButton);

        Allocation_pushButton = new QPushButton(layoutWidget);
        Allocation_pushButton->setObjectName(QString::fromUtf8("Allocation_pushButton"));
        sizePolicy1.setHeightForWidth(Allocation_pushButton->sizePolicy().hasHeightForWidth());
        Allocation_pushButton->setSizePolicy(sizePolicy1);
        Allocation_pushButton->setStyleSheet(QString::fromUtf8("border: 2px groove gray; border-radius: 10px; padding: 2px 4px"));

        verticalLayout_2->addWidget(Allocation_pushButton);

        scrollArea_2->setWidget(scrollAreaWidgetContents_2);
        Title_label = new QLabel(Basic_Data_Dialog);
        Title_label->setObjectName(QString::fromUtf8("Title_label"));
        Title_label->setGeometry(QRect(279, 10, 141, 20));
        QFont font1;
        font1.setPointSize(14);
        font1.setBold(true);
        font1.setWeight(75);
        Title_label->setFont(font1);
        Title_label->setStyleSheet(QString::fromUtf8("background:transparent"));

        retranslateUi(Basic_Data_Dialog);

        stackedWidget->setCurrentIndex(6);


        QMetaObject::connectSlotsByName(Basic_Data_Dialog);
    } // setupUi

    void retranslateUi(QWidget *Basic_Data_Dialog)
    {
        Basic_Data_Dialog->setWindowTitle(QApplication::translate("Basic_Data_Dialog", "Form", 0));
        label_3->setText(QApplication::translate("Basic_Data_Dialog", "\347\261\273\345\210\253\345\220\215\347\247\260\357\274\232", 0));
        label_4->setText(QApplication::translate("Basic_Data_Dialog", "\344\270\212\347\272\247\346\211\200\345\261\236\347\261\273\345\210\253\357\274\232", 0));
        Add_Category_pushButton->setText(QApplication::translate("Basic_Data_Dialog", "\346\267\273\345\212\240", 0));
        Modify_Category_pushButton->setText(QApplication::translate("Basic_Data_Dialog", "\344\277\256\346\224\271", 0));
        Save_Category_pushButton->setText(QApplication::translate("Basic_Data_Dialog", "\344\277\235\345\255\230", 0));
        Cancel_Category_pushButton_->setText(QApplication::translate("Basic_Data_Dialog", "\345\217\226\346\266\210", 0));
        Delete_Category_pushButton_->setText(QApplication::translate("Basic_Data_Dialog", "\345\210\240\351\231\244", 0));
        label_5->setText(QApplication::translate("Basic_Data_Dialog", "\351\242\234\350\211\262\345\220\215\347\247\260\357\274\232", 0));
        Cancel_Color_pushButton->setText(QApplication::translate("Basic_Data_Dialog", "\345\217\226\346\266\210", 0));
        Modify_Color_pushButton->setText(QApplication::translate("Basic_Data_Dialog", "\344\277\256\346\224\271", 0));
        Delete_Color_pushButton->setText(QApplication::translate("Basic_Data_Dialog", "\345\210\240\351\231\244", 0));
        Add_Color_pushButton->setText(QApplication::translate("Basic_Data_Dialog", "\346\267\273\345\212\240", 0));
        Save_Color_pushButton->setText(QApplication::translate("Basic_Data_Dialog", "\344\277\235\345\255\230", 0));
        Save_Unit_pushButton->setText(QApplication::translate("Basic_Data_Dialog", "\344\277\235\345\255\230", 0));
        Cancle_Unit_pushButton->setText(QApplication::translate("Basic_Data_Dialog", "\345\217\226\346\266\210", 0));
        Delete_Unit_pushButton->setText(QApplication::translate("Basic_Data_Dialog", "\345\210\240\351\231\244", 0));
        Add_Unit_pushButton->setText(QApplication::translate("Basic_Data_Dialog", "\346\267\273\345\212\240", 0));
        Modify_Unit_pushButton->setText(QApplication::translate("Basic_Data_Dialog", "\344\277\256\346\224\271", 0));
        label_6->setText(QApplication::translate("Basic_Data_Dialog", "\345\215\225\344\275\215\345\220\215\347\247\260\357\274\232", 0));
        Add_Unit_pushButton_2->setText(QApplication::translate("Basic_Data_Dialog", "\346\267\273\345\212\240", 0));
        Modify_Unit_pushButton_2->setText(QApplication::translate("Basic_Data_Dialog", "\344\277\256\346\224\271", 0));
        Save_Unit_pushButton_2->setText(QApplication::translate("Basic_Data_Dialog", "\344\277\235\345\255\230", 0));
        Cancle_Unit_pushButton_2->setText(QApplication::translate("Basic_Data_Dialog", "\345\217\226\346\266\210", 0));
        Delete_Unit_pushButton_2->setText(QApplication::translate("Basic_Data_Dialog", "\345\210\240\351\231\244", 0));
        label_7->setText(QApplication::translate("Basic_Data_Dialog", "\345\216\237\350\256\241\351\207\217\345\215\225\344\275\215\357\274\232", 0));
        label_8->setText(QApplication::translate("Basic_Data_Dialog", "\347\233\256\346\240\207\350\256\241\351\207\217\345\215\225\344\275\215\357\274\232", 0));
        label->setText(QApplication::translate("Basic_Data_Dialog", "\346\225\260\351\207\217\344\270\2721\347\232\204\345\216\237\350\256\241\351\207\217\345\215\225\344\275\215\347\232\204\345\225\206\345\223\201\345\217\257\346\213\206\344\270\272\347\233\256\346\240\207\350\256\241\351\207\217\345\215\225\344\275\215\345\225\206\345\223\201\346\225\260\351\207\217\357\274\232", 0));
        label_9->setText(QApplication::translate("Basic_Data_Dialog", "\345\216\237\345\225\206\345\223\201\346\235\241\347\240\201\357\274\232", 0));
        label_10->setText(QApplication::translate("Basic_Data_Dialog", "\347\233\256\346\240\207\345\225\206\345\223\201\346\235\241\347\240\201\357\274\232", 0));
        label_11->setText(QApplication::translate("Basic_Data_Dialog", "\345\216\237\345\225\206\345\223\201\345\220\215\347\247\260\357\274\232", 0));
        label_12->setText(QApplication::translate("Basic_Data_Dialog", "\347\233\256\346\240\207\345\225\206\345\223\201\345\220\215\347\247\260\357\274\232", 0));
        label_13->setText(QApplication::translate("Basic_Data_Dialog", "\346\213\206\345\214\205\346\227\266\346\243\200\346\237\245\345\216\237\345\225\206\345\223\201\347\232\204\345\214\271\351\205\215\346\226\271\345\274\217\357\274\232", 0));
        comboBox->clear();
        comboBox->insertItems(0, QStringList()
         << QApplication::translate("Basic_Data_Dialog", "\346\214\207\345\256\232\345\215\225\344\275\215\345\222\214\346\214\207\345\256\232\346\235\241\347\240\201", 0)
         << QApplication::translate("Basic_Data_Dialog", "\346\214\207\345\256\232\345\215\225\344\275\215\345\222\214\350\207\252\345\212\250\346\237\245\346\211\276\347\233\270\345\220\214\344\272\247\345\223\201", 0)
         << QApplication::translate("Basic_Data_Dialog", "\346\214\207\345\256\232\345\215\225\344\275\215\345\222\214\346\214\207\345\256\232\345\225\206\345\223\201\345\220\215\347\247\260", 0)
        );
        label_14->setText(QApplication::translate("Basic_Data_Dialog", "\345\220\215\347\247\260\357\274\232", 0));
        label_16->setText(QApplication::translate("Basic_Data_Dialog", "\345\234\260\345\235\200\357\274\232", 0));
        label_18->setText(QApplication::translate("Basic_Data_Dialog", "\347\224\265\345\255\220\351\202\256\344\273\266\357\274\232", 0));
        label_15->setText(QApplication::translate("Basic_Data_Dialog", "\350\201\224\347\263\273\344\272\272\357\274\232", 0));
        label_17->setText(QApplication::translate("Basic_Data_Dialog", "\347\224\265\350\257\235\357\274\232", 0));
        label_19->setText(QApplication::translate("Basic_Data_Dialog", "\345\244\207\346\263\250\357\274\232", 0));
        Add_Unit_pushButton_3->setText(QApplication::translate("Basic_Data_Dialog", "\346\267\273\345\212\240", 0));
        Modify_Unit_pushButton_3->setText(QApplication::translate("Basic_Data_Dialog", "\344\277\256\346\224\271", 0));
        Save_Unit_pushButton_3->setText(QApplication::translate("Basic_Data_Dialog", "\344\277\235\345\255\230", 0));
        Cancle_Unit_pushButton_3->setText(QApplication::translate("Basic_Data_Dialog", "\345\217\226\346\266\210", 0));
        Delete_Unit_pushButton_3->setText(QApplication::translate("Basic_Data_Dialog", "\345\210\240\351\231\244", 0));
        label_22->setText(QApplication::translate("Basic_Data_Dialog", "0-1\344\271\213\351\227\264\347\232\204\345\260\217\346\225\260\343\200\202\346\257\224\345\246\2020.85", 0));
        Add_Vip_pushButton->setText(QApplication::translate("Basic_Data_Dialog", "\346\267\273\345\212\240", 0));
        Modify_Vip_pushButton->setText(QApplication::translate("Basic_Data_Dialog", "\344\277\256\346\224\271", 0));
        Save_Vip_pushButton->setText(QApplication::translate("Basic_Data_Dialog", "\344\277\235\345\255\230", 0));
        Cancle_Vip_pushButton->setText(QApplication::translate("Basic_Data_Dialog", "\345\217\226\346\266\210", 0));
        Delete_Vip_pushButton->setText(QApplication::translate("Basic_Data_Dialog", "\345\210\240\351\231\244", 0));
        label_20->setText(QApplication::translate("Basic_Data_Dialog", "\347\261\273\345\210\253\345\220\215\347\247\260\357\274\232", 0));
        label_21->setText(QApplication::translate("Basic_Data_Dialog", "\351\273\230\350\256\244\346\212\230\346\211\243\357\274\232", 0));
        label_23->setText(QApplication::translate("Basic_Data_Dialog", "\347\261\273\345\210\253\345\220\215\347\247\260\357\274\232", 0));
        Add_Adjust_pushButton->setText(QApplication::translate("Basic_Data_Dialog", "\346\267\273\345\212\240", 0));
        Modify_Adjust_pushButton->setText(QApplication::translate("Basic_Data_Dialog", "\344\277\256\346\224\271", 0));
        Save_Adjust_pushButton->setText(QApplication::translate("Basic_Data_Dialog", "\344\277\235\345\255\230", 0));
        Cancle_Adjust_pushButton->setText(QApplication::translate("Basic_Data_Dialog", "\345\217\226\346\266\210", 0));
        Delete_Adjust_pushButton->setText(QApplication::translate("Basic_Data_Dialog", "\345\210\240\351\231\244", 0));
        label_24->setText(QApplication::translate("Basic_Data_Dialog", "\345\257\271\346\226\271\345\205\254\345\217\270\346\210\226\345\272\227\351\223\272\345\220\215\347\247\260\357\274\232", 0));
        Add_Allocation_pushButton->setText(QApplication::translate("Basic_Data_Dialog", "\346\267\273\345\212\240", 0));
        Modify_Allocation_pushButton->setText(QApplication::translate("Basic_Data_Dialog", "\344\277\256\346\224\271", 0));
        Save_Allocation_pushButton->setText(QApplication::translate("Basic_Data_Dialog", "\344\277\235\345\255\230", 0));
        Cancle_Allocation_pushButton->setText(QApplication::translate("Basic_Data_Dialog", "\345\217\226\346\266\210", 0));
        Delete_Allocation_pushButton->setText(QApplication::translate("Basic_Data_Dialog", "\345\210\240\351\231\244", 0));
        label_2->setText(QApplication::translate("Basic_Data_Dialog", "\345\223\201\347\211\214\345\220\215\347\247\260\357\274\232", 0));
        Add_Brand_pushButton->setText(QApplication::translate("Basic_Data_Dialog", "\346\267\273\345\212\240", 0));
        Modify_Brand_pushButton->setText(QApplication::translate("Basic_Data_Dialog", "\344\277\256\346\224\271", 0));
        Save_Brand_pushButton->setText(QApplication::translate("Basic_Data_Dialog", "\344\277\235\345\255\230", 0));
        Cancel_Brand_pushButton->setText(QApplication::translate("Basic_Data_Dialog", "\345\217\226\346\266\210", 0));
        Delete_Brand_pushButton->setText(QApplication::translate("Basic_Data_Dialog", "\345\210\240\351\231\244", 0));
        Brand_pushButton->setText(QApplication::translate("Basic_Data_Dialog", "\345\223\201\347\211\214\347\256\241\347\220\206", 0));
        Categoriy_pushButton->setText(QApplication::translate("Basic_Data_Dialog", "\347\261\273\345\210\253\347\256\241\347\220\206", 0));
        Color_pushButton->setText(QApplication::translate("Basic_Data_Dialog", "\351\242\234\350\211\262\347\256\241\347\220\206", 0));
        Unit_pushButton->setText(QApplication::translate("Basic_Data_Dialog", "\350\256\241\351\207\217\345\215\225\344\275\215", 0));
        Auto_pushButton->setText(QApplication::translate("Basic_Data_Dialog", "\350\207\252\345\212\250\346\213\206\345\214\205", 0));
        Supplier_pushButton->setText(QApplication::translate("Basic_Data_Dialog", "\344\276\233\350\264\247\345\225\206\347\256\241\347\220\206", 0));
        VIP_pushButton->setText(QApplication::translate("Basic_Data_Dialog", "VIP\344\274\232\345\221\230\347\261\273\345\210\253", 0));
        Adjust_pushButton->setText(QApplication::translate("Basic_Data_Dialog", "\345\272\223\345\255\230\350\260\203\346\225\264\347\261\273\345\210\253", 0));
        Allocation_pushButton->setText(QApplication::translate("Basic_Data_Dialog", "\345\272\223\345\255\230\350\260\203\346\213\250\345\257\271\350\261\241", 0));
        Title_label->setText(QString());
    } // retranslateUi

};

namespace Ui {
    class Basic_Data_Dialog: public Ui_Basic_Data_Dialog {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_BASIC_DATA_DIALOG_H
